---
title: 'Data preparation B'
author: ""
output:
    html_document:
        smart: false
editor_options:
  chunk_output_type: console
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE)
options(scipen=999)
rm(list=ls())
```


# Data preparation B: selects & recodes

## Libraries

```{r libraries}
library(sjlabelled)
library(dplyr)
library(haven)
library(descr)
library(sjmisc)

```



## Variables:

a- salaries perceived & just worker & manager
b- education
c- income
d- redistribution

## Year 1999

### Load data


```{r }
load("input/data/intermediate/cl99.RData") # cl99
```


### a- salaries perceived & just worker & manager

```{r }

# Find vars

find_var(cl99,"worker",search = "all") # v21: perceived worker, v31 just worker unrecoded
find_var(cl99,"chairman",search = "all") # v16: perceived chairman, v26 just chairman unrecoded


# Create object with vars & rename

dat99 <- cl99 %>% select(v21,v31,v16,v26) %>% rename(salperger=v16,
               salperobr=v21,
               saljusger=v26,
               saljusobr=v31)

# Recodes

stargazer(dat99, type="text")

dat99[][dat99  >= 99999999998] <- NA # missings

dat99 <- dat99 %>%
  mutate(salperobr=replace(salperobr, salperobr <= 40000 | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000, NA))

#---Brecha salarial percibida
dat99$gap_perc   <-  as.numeric(dat99$salperger/dat99$salperobr) # diferencia total
dat99$lngap_perc <-  as.numeric(log(dat99$gap_perc))                 # diferencia log

#---Brecha salarial justa
dat99$gap_just   <-  as.numeric(dat99$saljusger/dat99$saljusobr) # diferencia total
dat99$lngap_just <-  as.numeric(log(dat99$gap_just))                # diferencia log
dim(na.omit(dat99))
```

### b - education

```{r}

# Find vars

find_var(cl99,"degr",search = "all") # v21: perceived worker, v31 just worker
frq(as.factor(cl99$x_degr))
frq(as.factor(cl99$degree))

# Problema: no se encuentran los codigos originales en codebook, se derivan de la pregunta father education v317, que tiene las 7 categorías unesco asumiendo que las 7 de degree son las mismas:

# 1. None
# 2. Incomplete primary
# 3. Primary completed
# 4. Incomplete secondary (also includes completed qualifications at a level below academic secondary school
# completion – for example skilled manual qualifications given by trade schools.)
# 5. Secondary completed
# 6. Some tertiary education but less than a university Bachelor’s degree (Includes incomplete university. Also
# includes completed post-secondary courses below university Bachelor’s degree level. Examples are qualifications
# from US junior college, polytechnical institutes in many countries, and other similar post-secondary education.)
# 7. University completed (Bachelor’s degree or higher)

# Codificación original Francisco queda stand-by:

# #dat99 <- mutate(dat99, educ_rec = car::recode(dat99$educ, "3001:3004 = 1;  = 2;3008=2; 3010 = 3;3007 = 4"))
# dat99$educ_rec[dat99$educ_rec== 3001:3004 ] <- 1
# dat99$educ_rec[dat99$educ_rec== 3005:3006 ] <- 2
# dat99$educ_rec[dat99$educ_rec== 3008] <- 2
# dat99$educ_rec[dat99$educ_rec== 3010] <- 3
# dat99$educ_rec[dat99$educ_rec== 3007] <- 4

cl99 <- cl99 %>% select(degree) %>% mutate(educ_rec=rec(degree,rec = "1:4=1; 5=2 ; 6=3 ; 7=4"))

names(dat99)

dat99<-cbind(dat99,cl99 %>% select(educ_rec)) # add educ to table

summary(dat99)

dat99 %>% group_by(educ_rec) %>% summarize(m=median(gap_perc, na.rm = TRUE))
```

### c-income


```{r}

find_var(cl99,"income",search = "all") # v21: perceived worker, v31 just worker

freq(cl99$incomer) # deciles family
freq(cl99$rincomer) # deciles respondent, more missings
freq(cl99$income) # 14 categories family
freq(cl99$rincome) # categories respondent

# take income, impute middle range, then divide by persons in household, then deciles

cl99$income_c= rec(cl99$income,rec =   
      "1=45000;
      2=105500;
      3=135500;
      4=165500;
      5=195500;
      6=225500;
      7=265500;
      8=240500;
      9=495500;
      10=800500;
      11=1250000;
      12=1750000;
      13=2500000;
      14=4000000;
      999998=NA;
      999999=NA")

freq(cl99$income_c) # ok

find_var(cl99,"household",search = "all") # persons in household
freq(cl99$hompop)

dat99$ingreso_pc= cl99$income_c/cl99$hompop       

# Generar quintiles de ingreso

dat99 %>% mutate(Quint = ntile(ingreso_pc,5)) -> dat99

# Check
freq( dat99$Quint)

```


### d - redistribution

```{r}
find_var(cl99,"income",search = "all") # v35
freq(cl99$v35)
get_labels(cl99$v35,values = "as.name")

dat99$redis <-rec(cl99$v35, rec="8:9=NA;else=copy")
dat99$redis <-rec(dat99$redis, rec="rev")
freq(dat99$redis)
dat99$redis <-set_labels(dat99$redis,labels= c("Muy en desacuerdo"=1, "En descacuerdo"=2,"Ni acuerdo ni desacuerdo"=3, "De acuerdo"=4, "Muy de acuerdo"=5))
get_labels(dat99$redis, values="as.name")
freq(to_label(dat99$redis))
```
### e - estatus subjetivo

dat99$v46 <- car::recode(dat99$v46,"c(97,98,99)=NA",as.numeric = TRUE)
dat99$v46 <- sjmisc::rec(dat99$v46,rec="rev") # La escala estaba invertida
dat99 <- cl99 %>% rename(ess=v46)


### Save 99 data


```{r}
save(dat99,file = "input/data/processed/dat99.RData")

```

## Year 2009

```{r agno 2009}

#sjPlot::view_df(cl09, show.frq = T, max.len = 100000)

dat09 <- cl09 %>% dplyr::select(v5,
                         v23,v25, # Salario percibido obrero y gerente
                         v28,v30, # Salario justo     obrero y gerente
                         v33, # redistribucion
                         cl_degr, #Educacion
                         cl_inc, #ingreso
                         v44, #estatus subjetivo
                         v10) # meritocracia

#--- missing meritocracia -------------------------------------------------#
# Percepcion

#dat09$cl_inc  <- car::recode(dat09$cl_inc ,"c(9999998, 9999999)=NA",as.numeric = TRUE) # Recodificación missing
dat09$cl_inc[dat09$cl_inc==9999998]<-NA
dat09$cl_inc[dat09$cl_inc==9999999]<-NA

#dat09$educ_rec <- car::recode(dat09$educ_rec,"c(99)=NA",as.numeric = TRUE)
dat09$cl_inc[dat09$cl_inc==99]<-NA


#dat09$v10 <- car::recode(dat09$v10,"c(8,9)=NA",as.numeric = TRUE)
dat09$v10[dat09$v10==8]<-NA
dat09$v10[dat09$v10==9]<-NA
dat09$v10 <-sjmisc::rec(dat09$v10,rec="rev")# invertir sentido escala


# Redistribucion
#dat09$v33 <- car::recode(dat09$v33,"c(8,9)=NA",as.numeric = TRUE)
dat09$v33[dat09$v33==8]<-NA
dat09$v33[dat09$v33==9]<-NA

dat09$v33 <- sjmisc::rec(dat09$v33,rec="rev")
# Estatus subj 
dat09$v44 <- car::recode(dat09$v44,"c(97,98,99)=NA",as.numeric = TRUE)

# Rename variables

dat09 <- dplyr::rename(dat09,
                       pais=v5,
                salperger=v23,
                salperobr=v25,
                saljusger=v28,
                saljusobr=v30,
                permer=v10,
                redis= v33,
                educ_rec = cl_degr,
                ess=v44,
                income = cl_inc)


#--- missing brechas -------------------------------------------------#
dat09 <- dat09 %>%
  mutate(salperobr=replace(salperobr, salperobr <= 40000 | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000, NA))
#---Brecha salarial percibida
dat09$gap_perc   <-  as.numeric(dat09$salperger/dat09$salperobr) # diferencia total
dat09$lngap_perc <-  as.numeric(log(dat09$gap_perc))                # diferencia log
#---Brecha salarial justa
dat09$gap_just   <-  as.numeric(dat09$saljusger/dat09$saljusobr) # diferencia total
dat09$lngap_just <-  as.numeric(log(dat09$gap_just))                # diferencia log
dim(na.omit(dat09))

#---Recodificacion Educacion

#dat09 <- mutate(dat09, educ_rec = car::recode(dat09$cl_degr, "0:3 = 1; 4:5 = 2; 7=2; 6 =3;8:9=4"))
dat09$educ_rec[dat09$educ_rec== 0:3] <- 1
dat09$educ_rec[dat09$educ_rec== 4:5] <- 2
dat09$educ_rec[dat09$educ_rec== 7] <- 2
dat09$educ_rec[dat09$educ_rec== 6] <- 3
dat09$educ_rec[dat09$educ_rec== 8:9] <- 4


#dat09 <- mutate(dat09, income = car::recode(dat09$income, "20000 = 1; 45000 = 2; 66000=3;90000= 4 ;122000 = 5;  155000 = 6; 200000 = 7; 250000 = 8; 310000 = 9; 400000= 10; 750000 = 11; 1500000 = 12; 2500000 = 13; 3100000 = 14" ))

dat09$income[dat09$income== 20000] <- 1
dat09$income[dat09$income== 45000] <- 2
dat09$income[dat09$income== 66000] <- 3
dat09$income[dat09$income== 90000] <- 4
dat09$income[dat09$income== 122000] <- 5
dat09$income[dat09$income== 155000] <- 6
dat09$income[dat09$income== 200000] <- 7
dat09$income[dat09$income== 250000] <- 8
dat09$income[dat09$income== 310000] <- 9
dat09$income[dat09$income== 400000] <- 10
dat09$income[dat09$income== 750000] <- 11
dat09$income[dat09$income== 1500000] <-12
dat09$income[dat09$income== 2500000] <- 13
dat09$income[dat09$income== 3100000] <- 14

#sjPlot::view_df(dat09, show.frq = T, max.len = 100000)

```

```{r }

#dicotomizar
#redis

dat09$redis<-ifelse(dat09$redis>=8,1,0)


######--------#Educación

dat09$universitaria<-ifelse(dat09$educ_rec==4,1,0)
dat09$tecnico<-ifelse(dat09$educ_rec==3,1,0)
dat09$media<-ifelse(dat09$educ_rec==2,1,0)
dat09$basica<-ifelse(dat09$educ_rec==1,1,0)


#permerit
dat09$permer<-ifelse(dat09$permer>=8,1,0)


####----#Income

#dat09 <- mutate(dat09, income_rec = car::recode(dat09$income, "1:4 = 1; 5:6 = 2; 7:8=3; 9:10=4; 11=5; 12:14=6"))

dat09$income_rec[dat09$income== 1:4] <- 1
dat09$income_rec[dat09$income== 5:6] <- 2
dat09$income_rec[dat09$income== 7:8] <- 3
dat09$income_rec[dat09$income== 9:10] <- 4
dat09$income_rec[dat09$income== 11] <- 5
dat09$income_rec[dat09$income== 12:14] <- 6

dat09$bajo <- ifelse(dat09$income_rec==1,1,0)
dat09$mediobajo <- ifelse(dat09$income_rec==2,1,0)
dat09$medio <- ifelse(dat09$income_rec==3,1,0)
dat09$medioalto <- ifelse(dat09$income_rec==4,1,0)
dat09$alto <- ifelse(dat09$income_rec==5,1,0)
dat09$muyalto <- ifelse(dat09$income_rec==6,1,0)


hist(dat09$redis)
```

```{r agno 2019}

dat19 <- cl19 %>% dplyr::select(m2_p2_presidente,m2_p2_obrero,  # Salario percibio obrero y gerente
                         m2_p3_presidente,m2_p3_obrero,  # Salario justo    obrero y gerente
                         m2_p4_2, # redistribucion
                         m2_p13a, #Estatus subjetivo
                         ds_p4, # Educacion
                         ds_p39, #ingreso
                         m2_p1_5) # meritocracia
#--- missing meritocracia -------------------------------------------------#
# Percepcion

#dat19$ds_p39  <- car::recode(dat19$ds_p39 ,"c(88, 99)=NA",as.numeric = TRUE) # Recodificación missing
dat19$ds_p39[dat19$ds_p39==88]<-NA
dat19$ds_p39[dat19$ds_p39==99]<-NA

#dat19$m2_p1_5  <- car::recode(dat19$m2_p1_5  ,"c(8,9)=NA",as.numeric = TRUE)
dat19$m2_p1_5[dat19$m2_p1_5==8]<-NA
dat19$m2_p1_5[dat19$m2_p1_5==9]<-NA
dat19$m2_p1_5  <-sjmisc::rec(dat19$m2_p1_5 ,rec="rev")# invertir sentido escala

#dat19$educ_rec <- car::recode(dat19$educ,"c(99)=NA",as.numeric = TRUE)
dat19$ds_p4[dat19$ds_p4==99]<-NA

#Redistribucion
#dat19$m2_p4_2 <- car::recode(dat19$m2_p4_2 ,"c(8,9)=NA",as.numeric = TRUE)
dat19$m2_p4_2[dat19$m2_p4_2==8]<-NA
dat19$m2_p4_2[dat19$m2_p4_2==9]<-NA
dat19$m2_p4_2  <-sjmisc::rec(dat19$m2_p4_2 ,rec="rev")# invertir sentido escala

# Estatus subjetivo

dat19$m2_p13a <- car::recode(dat19$m2_p13a ,"c(88,99)=NA",as.numeric = TRUE)


# Rename variables
dat19 <- dplyr::rename(dat19,
                salperger=m2_p2_presidente,
                salperobr=m2_p2_obrero,
                saljusger=m2_p3_presidente,
                saljusobr=m2_p3_obrero,
                ess=m2_p13a,    
                permerit=m2_p1_5 ,
                redis = m2_p4_2,
                income = ds_p39,
                educ_rec=ds_p4)
#--- missing brechas -------------------------------------------------#
dat19 <- dat19 %>%
  mutate(salperobr=replace(salperobr, salperobr <= 40000 | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000, NA))
#---Brecha salarial percibida
dat19$gap_perc   <-  as.numeric(dat19$salperger/dat19$salperobr) # diferencia total
dat19$lngap_perc <-  as.numeric(log(dat19$gap_perc))                  # diferencia log
#---Brecha salarial justa
dat19$gap_just   <-  as.numeric(dat19$saljusger/dat19$saljusobr) # diferencia total
dat19$lngap_just <-  as.numeric(log(dat19$gap_just))                # diferencia log

#----Educ_rec
#dat19 <- mutate(dat19, educ_rec = car::recode(dat19$educ, "0:3 = 1; 4:5 = 2; 7=2; 6 =3;8:9=4"))

dat19$educ_rec[dat19$educ_rec== 0:3] <- 1
dat19$educ_rec[dat19$educ_rec== 4:5] <- 2
dat19$educ_rec[dat19$educ_rec== 7] <- 2
dat19$educ_rec[dat19$educ_rec== 6] <- 3
dat19$educ_rec[dat19$educ_rec== 8:9] <- 4

table(dat19$salperobr)

#sjPlot::view_df(dat19, show.frq = T, max.len = 10000)
```

```{r }
## dummy

#redis
dat19$redis<-ifelse(dat19$redis>=8,1,0)
hist(dat19$redis)

######--------#Educación
dat19$universitaria<-ifelse(dat19$educ_rec==4,1,0)
dat19$tecnico<-ifelse(dat19$educ_rec==3,1,0)
dat19$media<-ifelse(dat19$educ_rec==2,1,0)
dat19$basica<-ifelse(dat19$educ_rec==1,1,0)

#basica de referencia
#permerit
dat19$permer<-ifelse(dat19$permerit>=8,1,0)
hist(dat19$permer)

####----#Income

#dat19 <- mutate(dat19, income_rec = car::recode(dat19$income, "1:4 = 1; 5:6 = 2; 7:8=3; 9:10=4; 11=5; 12:14=6"))

dat19$income_rec[dat19$income== 1:4] <- 1
dat19$income_rec[dat19$income== 5:6] <- 2
dat19$income_rec[dat19$income== 7:8] <- 3
dat19$income_rec[dat19$income== 9:10] <- 4
dat19$income_rec[dat19$income== 11] <- 5
dat19$income_rec[dat19$income== 12:14] <- 6

dat19$bajo <- ifelse(dat19$income_rec==1,1,0)
dat19$mediobajo <- ifelse(dat19$income_rec==2,1,0)
dat19$medio <- ifelse(dat19$income_rec==3,1,0)
dat19$medioalto <- ifelse(dat19$income_rec==4,1,0)
dat19$alto <- ifelse(dat19$income_rec==5,1,0)
dat19$muyalto <- ifelse(dat19$income_rec==6,1,0)
```


```{r}
dat99$year <- 1999
dat09$year <- 2009
dat19$year <- 2019
clw3<- bind_rows(dat99,dat09)
clw3<- bind_rows(clw3,dat19)
clw3 <- clw3 %>%  select(year,"salperobr","salperger","saljusobr","saljusger","gap_perc","lngap_perc","gap_just","lngap_just", "educ_rec", "income", everything())
save(clw3,file = "../input/data/dataproc/issp9919.RData")
save(dat99,file = "../input/data/dataproc/dat99.RData")
save(dat09,file = "../input/data/dataproc/dat09.RData")
save(dat19,file = "../input/data/dataproc/dat19.RData")
```

# tratamiento CASEN 2000-2017

##Casen 2000
```{r}
load(file="../input/data/origin data/datacasen/casen2000.RData")

#sjPlot::view_df(select(cs2000, "o8"), show.values = T, show.labels = T, max.len = 1000)
                #hacer codebook para o8

#peones de...
casen_obreros2000 = cs2000 %>% dplyr::filter(o8>=9210, o8<=9322)
casen_obreros2000 <- casen_obreros2000 %>% dplyr::select(yopraj)
casen_obreros2000<- na.omit(casen_obreros2000)

#gerentes de
casen_gerente2000 = cs2000 %>% dplyr::filter(o8==1210) #gerente empresa
#casen_gerente2000 <- casen_gerente2000 %>% dplyr::select(yopraj,o13,o10,o28, o11)

casen_gerente2000 = casen_gerente2000 %>% dplyr::filter(o10==1)
casen_gerente2000 = casen_gerente2000 %>% dplyr::filter(o13=="E" )

brecha_real2000<-(median(casen_gerente2000$yopraj))/(median(casen_obreros2000$yopraj))

summary(casen_obreros2000$yopraj)
summary(casen_gerente2000$yopraj)
summary(brecha_real2000)
table(casen_gerente2000$o13)

sjPlot::view_df(casen_gerente2000, show.frq = T, max.len = 100000)#hacer codebook
```
##Casen 2009

```{r}
load(file="../input/data/origin data/datacasen/casen2009.RData")
```
#
```{r}
#sjPlot::view_df(select(cs2009, "c_o12"), show.values = T, show.labels = T, max.len = 1000)

#ocupacion:c_o12
#ingreso: yopraj

#peones de...
casen_obreros2009 = cs2009 %>% dplyr::filter(c_o12>=9200, c_o12<=9322)
casen_obreros2009 <- casen_obreros2009 %>% dplyr::select(yopraj)
casen_obreros2009<- na.omit(casen_obreros2009)

#gerentes de
casen_gerente2009 = cs2009 %>% dplyr::filter(c_o12==1210) #gerente general empresa
casen_gerente2009 <- casen_gerente2009 %>% dplyr::select(yopraj,o14,o23)
casen_gerente2009 = casen_gerente2009 %>% dplyr::filter(o14=="F")    #gran empresa | cuando se utilizan los dos filtros se llega  a una brecha de 52
casen_gerente2009 = casen_gerente2009 %>% dplyr::filter(o23==1)      # filtro por ser patron en la empresa.
casen_gerente2009<-na.omit(casen_gerente2009)
table(casen_gerente2009$o14)
sjPlot::view_df(casen_gerente2009, show.frq = T, max.len = 1000)

brecha_real2009<-(median(casen_gerente2009$yopraj))/(median(casen_obreros2009$yopraj))

summary(casen_obreros2009$yopraj)
summary(casen_gerente2009$yopraj)
brecha_real2009
sjPlot::view_df(casen_gerente2009, show.frq = T, max.len = 300) # hacer codebook
```

9200
9210
9211
9212
9213
9300
9310
9311
9312
9313
9320
9321
9322
9330

```{r}
load(file="../input/data/origin data/datacasen/casen2017.RData")
```

## Casen 2017
```{r}
#codecasen17<-sjPlot::view_df(cs2017)#hacer codebook
#sjPlot::view_df(cs2017, show.values = T, show.labels = T, max.len = 1000)
                #hacer codebook para o8

#peones de...
casen_obreros2017 = cs2017 %>% dplyr::filter(oficio4>=9211, oficio4<=9322)
casen_obreros2017 <- casen_obreros2017 %>% dplyr::select(y0101, o23)
casen_obreros2017<- na.omit(casen_obreros2017)

#gerentes de
#casen_gerente2017 = cs2017 %>% dplyr::filter(oficio4 %in% c(1210:1319)) # Filtro con todos los gerentes
casen_gerente2017 = cs2017 %>% dplyr::filter(oficio4==1210) #gerente empresa
casen_gerente2017 <- casen_gerente2017 %>% dplyr::select(oficio4, y0101,o23, o15,yrut,y0701,y0801)
casen_gerente2017 = casen_gerente2017 %>% dplyr::filter(o23=="F") #gran empresa > 100 trabajadores
casen_gerente2017 = casen_gerente2017 %>% dplyr::filter(o15 == 1) # empleador

#casen_gerente2017 = casen_gerente2017 %>% dplyr::filter(y0701 <= 1000000) # empleador



# yrut # retiro de utilidades
#y0701 #independiente principal
#table(casen_gerente2017$o15)
# sjPlot::view_df(casen_gerente2017, show.frq = T, max.len = 1000)

brecha_real2017<-(median(casen_gerente2017$y0701,na.rm = T))/(median(casen_obreros2017$y0101,na.rm = T))

summary(casen_obreros2017$y0101)
table(casen_gerente2017$y0701)
brecha_real2017

summary(cs2017$y0101)
summary(cs2017$y0701)

```


```{r}
brecha_salarial<- rbind(psych::describe(brecha_real2000),
               psych::describe(brecha_real2009),
               psych::describe(brecha_real2017))

save(brecha_salarial, file = "../input/data/dataproc/dataproccasen/brecha.Rdata")
```


```{r}
salario_gerente<- rbind(psych::describe(casen_gerente2000$yopraj),
               psych::describe(casen_gerente2009$yopraj),
               psych::describe(casen_gerente2017$y0701))

save(salario_gerente, file = "../input/data/dataproc/dataproccasen/salario_gerente.Rdata")
```


```{r}
salario_obrero<- rbind(psych::describe(casen_obreros2000$yopraj),
               psych::describe(casen_obreros2009$yopraj),
               psych::describe(casen_obreros2017$y0101))

save(salario_obrero, file = "../input/data/dataproc/dataproccasen/salario_obrero.Rdata")
```


```{r}
hist(dat99$redis)
hist(dat09$saljusger)
hist(dat19$saljusger)
```
